repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.4
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: trailing-whitespace

- repo: local
  hooks:
  - id: check-types
    name: check types
    language: system
    entry: uv run ty check
